global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 1m

scrape_configs:
  - job_name: tfa-scrape
  - static_configs:
      - targets:
          - host.docker.internal: 5032
        -labels:
          app: tfa-local

      - targets:
          - tfa-api:8080
        -labels:
          app: tfa-docker
      